inherit_gem:
  rubocop-shopify: rubocop.yml

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.1

Layout/EmptyLineAfterGuardClause:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassMethodsDefinitions:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true
  Exclude:
    - "db/**/*.rb"
    - "spec/**/*.rb"
  AllowedMethods:
    - puts
    - raise
    - snapshot_test
    - write_to

# TODO: Maybe enable
Style/RaiseArgs:
  Enabled: false

Naming/FileName:
  Enabled: true
  Exclude:
    - "lib/jsonapi-resources-anchor.rb"
