inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1

Layout/EmptyLineAfterGuardClause:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/ClassMethodsDefinitions:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true
  Exclude:
    - "db/**/*.rb"
    - "spec/**/*.rb"
  AllowedMethods:
    - raise
