require "anchor/types"
require "anchor/anchor"
require "anchor/config"
require "anchor/schema_generator"
require "anchor/concerns/annotatable"
require "anchor/concerns/typeable"
require "anchor/concerns/custom_linkable"
require "anchor/concerns/custom_meta"
require "anchor/concerns/static_context"
require "anchor/concerns/type_inferable"
require "anchor/concerns/schema_serializable"
require "anchor/schema"
require "anchor/types/inference/active_record"
require "anchor/types/inference/rbs"
require "anchor/type_script/file_structure"
require "anchor/type_script/types"
require "anchor/type_script/schema_generator"
require "anchor/type_script/multifile_save_service"
require "anchor/type_script/multifile_schema_generator"
require "anchor/type_script/serializer"
require "anchor/type_script/resource"
require "anchor/json_schema/serializer"
require "anchor/json_schema/schema_generator"
require "anchor/json_schema/resource"

require "anchor/inference/active_record/types"
require "anchor/inference/active_record/types/base"
require "anchor/inference/active_record/types/column_comments"
require "anchor/inference/active_record/types/presence_required"
require "anchor/inference/active_record/types/serialized"
require "anchor/inference/active_record/types/defaulted"
require "anchor/inference/active_record/types/overridden"

require "anchor/inference/active_record/infer"
require "anchor/inference/active_record/infer/base"
require "anchor/inference/active_record/infer/columns"
require "anchor/inference/active_record/infer/model"
require "anchor/inference/active_record/infer/enums"
require "anchor/inference/active_record/infer/rbs"

require "anchor/inference/jsonapi/types"
require "anchor/inference/jsonapi/types/base"
require "anchor/inference/jsonapi/types/active_record_relationships_wrapper"
require "anchor/inference/jsonapi/types/relationships_wrapper"
require "anchor/inference/jsonapi/types/empty"
require "anchor/inference/jsonapi/types/overridden"
require "anchor/inference/jsonapi/types/anchor_comments"
require "anchor/inference/jsonapi/types/readable"

require "anchor/inference/jsonapi/infer"
require "anchor/inference/jsonapi/infer/base"
require "anchor/inference/jsonapi/infer/anchor_def"
require "anchor/inference/jsonapi/infer/shell"
require "anchor/inference/jsonapi/infer/rbs"
require "anchor/inference/jsonapi/infer/relationship_references"
require "anchor/inference/jsonapi/infer/resource"

require "anchor/inference/jsonapi/read_type"
